name: Build and Attach PDF to Release

on:
  push:
    tags:
      - "v*.*.*"  

jobs:
  build_pdf:
    runs-on: ubuntu-latest
    name: Build and Attach Documentation PDF
    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Setup Ruby and Gems
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true
      
      - name: Install Asciidoctor-PDF
        run: gem install asciidoctor asciidoctor-pdf

      # Step 3: Generate PDF from AsciiDoc
      - name: Generate PDF from AsciiDoc
        run: |
          mkdir -p docs
          asciidoctor-pdf -o docs/documentation.pdf src/asciidoc/main.adoc

      # Step 5: Upload PDF to GitHub Release
      - name: Upload PDF to Release
        uses: softprops/action-gh-release@v1
        with:
          files: docs/documentation.pdf 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
