name: Build AsciiDoc to PDF

on:
  push:
    branches:
      - main

jobs:
  adoc_build_pdf:
    runs-on: ubuntu-latest
    name: Build AsciiDoc to PDF
    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Setup Ruby and Gems
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true
      
      - name: Install Asciidoctor-PDF
        run: gem install asciidoctor asciidoctor-pdf

      # Step 3: Generate PDF from AsciiDoc
      - name: Generate PDF from AsciiDoc
        run: |
          mkdir -p output
          asciidoctor-pdf -o output/documentation.pdf src/asciidoc/main.adoc

      # Step 4: Deploy PDF to GitHub Pages
      - name: Deploy PDF to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./output
