name: build adocs

on:
  push:
    branches:
      - main

jobs:
  adoc_build:
    runs-on: ubuntu-latest
    name: Build AsciiDoc to HTML
    steps:
      # 1. Récupérer le code source
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Construire le fichier HTML avec Asciidoctor
      - name: Build AsciiDoc
        id: adocbuild
        uses: tonynv/asciidoctor-action@master
        with:
          program: "asciidoctor -D docs --backend=html5 -o main.html src/asciidoc/main.adoc"

      # 3. Imprimer l'heure d'exécution
      - name: Print execution time
        run: echo "Time ${{ steps.adocbuild.outputs.time }}"

      # 4. Déployer vers GitHub Pages
      - name: Deploy docs to ghpages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./docs
