name: build adocs to PDF

on:
  push:
    branches:
      - main

jobs:
  adoc_build_pdf:
    runs-on: ubuntu-latest
    name: Build AsciiDoc to PDF
    steps:
      # 1. Récupérer le code source
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Installer Asciidoctor et Asciidoctor-PDF
      - name: Install Asciidoctor-PDF
        run: |
          sudo apt-get update
          sudo apt-get install -y ruby
          gem install asciidoctor asciidoctor-pdf

      # 3. Générer le PDF
      - name: Generate PDF from AsciiDoc
        run: |
          mkdir -p output
          asciidoctor-pdf -o output/documentation.pdf src/asciidoc/main.adoc

      # 4. Déployer le PDF sur GitHub Pages
      - name: Deploy PDF to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./output
