name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '21'

      # Ajout d'une étape pour vérifier que Gradle est installé et accessible
      - name: Check Gradle version
        run: ./gradlew -v

      # Exécution de la construction du backend
      - name: Build Backend
        working-directory: ./fiveMusic
        run: ./gradlew buildBackend
        continue-on-error: true  # Permet de continuer si une erreur se produit pour vérifier l'erreur

      - name: Test Backend
        working-directory: ./fiveMusic
        run: ./gradlew testBackend
        continue-on-error: true

      # Ajout d'une étape pour vérifier que les fichiers du frontend sont accessibles
      - name: List files in frontend
        working-directory: ./fiveMusic-frontend
        run: ls -la

      # Exécution de la construction du frontend
      - name: Build Frontend
        working-directory: ./fiveMusic-frontend
        run: ./gradlew buildFrontend
        continue-on-error: true

      - name: Test Frontend
        working-directory: ./fiveMusic-frontend
        run: ./gradlew testFrontend
        continue-on-error: true
