name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'

      - name: Build Backend
        working-directory: ./fiveMusic
        run: ./gradlew buildBackend

      - name: Test Backend
        working-directory: ./fiveMusic
        run: ./gradlew testBackend

      - name: Build Frontend
        working-directory: ./fiveMusic-frontend
        run: ./gradlew buildFrontend

      - name: Test Frontend
        working-directory: ./fiveMusic-frontend
        run: ./gradlew testFrontend
